### ISSUE TITLE
 The problem with installing the module and does not work on servers

### ISSUE THREAD

**Issue by Incognito00** [AngelSecurityTeam/Recreator-Phishing#1]
The problem with installing the module: (my server ubuntu 18)
Traceback (most recent call last):
  File "ServerInstall.py", line 5, in <module>
    from module import download
ModuleNotFoundError: No module named 'module'
![2019-12-10_0239](https://user-images.githubusercontent.com/53401121/70479690-d14c0d80-1ad5-11ea-9c14-457ce98c1661.png)

does not work on servers SERVEO, LOCALXPOSE and NGROK:
![2019-12-10_0225](https://user-images.githubusercontent.com/53401121/70479715-de68fc80-1ad5-11ea-90af-e4456efa741b.png)

**Comment by AngelSecurityTeam** [comment]
Serveo is temporarily disabled due to phishing.

Serveo will return in a few days with a few new restrictions to help
dissuade abuse. Thanks for your patience!
