### ISSUE TITLE
No Start Server

### ISSUE THREAD

**Issue by Lorenz11x** [AngelSecurityTeam/Recreator-Phishing#4]
Hi, does not work, does not start the choice of the server but provides the folder with the index.html and robots.txt files.
Because? Thanks in advance :+1: 

GnuTLS: Resource temporarily unavailable, try again.
GnuTLS: Resource temporarily unavailable, try again.
2020-04-13 12:08:41 URL:https://facebook.com/robots.txt [10625] -> "/root/

**Comment by AngelSecurityTeam** [comment]
it is not a problem .. only if your connection is unstable ... in the same way it will try to finish the process  [CAP](https://i.ibb.co/b7XTjYZ/1111.png)

**Comment by Lorenz11x** [comment]
Hello Mister
thank you for your kind reply, however I downloaded
Recreator-Phishing-master.zip, extracted and installed it and it works
perfectly !! compliments !! ;)

Il giorno mar 14 apr 2020 alle ore 18:53 AngelSecurityTeam <
notifications@github.com> ha scritto:

**Comment by Lorenz11x** [comment]
.... excuse me a question, why in VM does Kali Linux work and on Kali Linux
installed on hard disk it does not work ??
they are both connected to the same wifi
Photo 1 and Photo 2

Tanks !! ;)

Il giorno mar 14 apr 2020 alle ore 18:53 AngelSecurityTeam <
notifications@github.com> ha scritto:
