### ISSUE TITLE
ngrok don't connect

### ISSUE THREAD

**Issue by arsenidzee** [AngelSecurityTeam/Recreator-Phishing#5]
Hi bro, sorry for my English, I don't speak it well. I encountered such a problem when I entered the address of the site, in the options section I select ngrok and every time I encounter this, could you tell me how to solve it?![image](https://user-images.githubusercontent.com/64613247/81507235-9d834700-9304-11ea-8c71-6aeb143f9bd5.jpeg)

**Comment by AngelSecurityTeam** [comment]
log in; https://dashboard.ngrok.com/signup; and generate your token
